<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers.MsSql" />
        <PackageReference Include="Microsoft.SqlServer.DacFx" />
    </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SqlServer\GtMotive.bacpac">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
